/* Automatically generated by 'scripts/build/bin/build-entry.js' */

import Element1Button from '../packages/element1-button/index.js';
import Element1Container from '../packages/element1-container/index.js';
import Element1Layout from '../packages/element1-layout/index.js';

const components = [
  Element1Button,
  Element1Container,
  Element1Layout,
];

const install = function(Vue, opts = {}) {
  if (install.installed) return
  install.installed = true
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  version: '0.0.0',
  Element1Button,
  Element1Container,
  Element1Layout
};
